site_name: Pulp Operator
site_description: Pulp Operator
site_author: Pulp Team
site_url: https://docs.pulpproject.org/pulp_operator/
repo_name: pulp/pulp-operator
repo_url: https://github.com/pulp/pulp-operator
theme: readthedocs
nav:
  - Home: index.md
  - Getting Started: quickstart.md
  - Contributing: contributing.md
  - Containers: container.md
  - Custom Resources:
      - Pulp:
        - API: roles/pulp-api.md
        - Content: roles/pulp-content.md
        - Resource Manager: roles/pulp-resource-manager.md
        - Routes: roles/pulp-routes.md
        - Worker: roles/pulp-worker.md
        - Web: roles/pulp-web.md
        - Status: roles/pulp-status.md
        - Postgres: roles/postgres.md
        - Redis: roles/redis.md
      - Pulp Backup:
        - Backup: roles/backup.md
      - Pulp Restore:
        - Restore: roles/restore.md
  - Changelog: CHANGES.md
markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.superfences
