---
- hosts: localhost
  gather_facts: no
  collections:
    - community.kubernetes
    - operator_sdk.util
  vars:
    project_name: "{{ meta.namespace }}"
    default_settings:
      db_encryption_key: "/etc/pulp/keys/database_fields.symmetric.key"
      databases:
        default:
          HOST: "{{ postgres_host }}"
          ENGINE: django.db.backends.postgresql_psycopg2
          NAME: "{{ postgres_database }}"
          USER: "{{ postgres_user }}"
          PASSWORD: "{{ postgres_pass }}"
          PORT: "{{ postgres_port }}"
          CONN_MAX_AGE: 0
      redis_host: "{{ meta.name }}-redis"
      redis_port: 6379
      redis_password: ""
      GALAXY_FEATURE_FLAGS:
        execution_environments: ""
    deployment_state: present
    registry: quay.io
    project: pulp
    image: pulp
    image_web: pulp-web
    image_pull_secret: ""
    tag: stable
    storage_type: File
    file_storage_access_mode: "ReadWriteMany"
    file_storage_size: "100Gi"
  roles:
    - postgres
    - redis
    - pulp-routes
    - pulp-web
    - pulp-api
    - pulp-content
    - pulp-resource-manager
    - pulp-worker
    - pulp-status
