---
- name: Load Route TLS certificate
  include_tasks: load_route_tls_secret.yml
  when:
    - ingress_type | lower == 'route'
    - route_tls_secret != ''

- name: Gathering routes
  include_tasks: load_routes.yml
  vars:
    max_retries: 5
    retry_delay: 5
  # when:
  #   - ingress_type | lower == 'route'

- name: debug routes
  debug:
    var: _pulp_plugins

- name: pulp routes
  k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.ingress.yaml.j2') }}"
  with_items:
    - pulp
  when:
    - ingress_type is defined
    - ('route' == ingress_type|lower) or ('ingress' == ingress_type|lower)
