---
- set_fact:
    fingress_type: 'ingress'

- name: pulp routes
  k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.ingress.yaml.j2') | from_yaml }}"
  with_items:
    - pulp
  when:
    - fingress_type is defined
    - ('route' == fingress_type|lower) or ('ingress' == fingress_type|lower)
