images:
  - pulp_web_master:
      image_name: pulp-web
      tag: 0.3.0
      container_file: Containerfile.web
      base_image_name: pulp
      python_version: "3.9"
      plugin_snippets:
        - pulp_ansible
        - pulp_container
        - pulp_python
registry: quay.io
project: pulp
