---
content:
  replicas: 2
  log_level: INFO
  resource_requirements:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 800m
      memory: 4Gi

ingress_type: none
is_file_storage: true

# Here we use  _pulpproject_org_pulp to get un-modified cr
# see: https://github.com/operator-framework/operator-sdk/issues/1770
raw_spec: "{{ vars['_pulpproject_org_pulp']['spec'] }}"
