---
content:
  replicas: 2
  log_level: INFO
  resource_requirements:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 800m
      memory: 1Gi

ingress_type: none
is_file_storage: true
