---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulp-operator
  annotations:
    email: pulp-dev@redhat.com
  labels:
    app.kubernetes.io/name: pulp-operator
    app.kubernetes.io/component: operator
    owner: pulp-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pulp-operator
      app.kubernetes.io/component: operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pulp-operator
        app.kubernetes.io/component: operator
    spec:
      serviceAccountName: pulp-operator
      containers:
        - name: pulp-operator
          image: "quay.io/pulp/pulp-operator:latest"
          # securityContext: # FIXME: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
          #   runAsUser: 1000
          #   runAsNonRoot: true
          #   readOnlyRootFilesystem: true
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 150m
              memory: 256Mi
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "pulp-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: ANSIBLE_DEBUG_LOGS
              value: 'false'
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 6789
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: runner
          emptyDir: {}
