apiVersion: pulp.pulpproject.org/v1beta1
kind: Pulp
metadata:
  name: ocp-example
spec:
  image: quay.io/pulp/galaxy
  image_web: quay.io/pulp/galaxy-web
  no_log: false
  admin_password_secret: "example-pulp-admin-password"
  storage_type: File
  ingress_type: route
  route_tls_termination_mechanism: edge
  # k3s local-path requires this
  file_storage_access_mode: "ReadWriteOnce"
  file_storage_storage_class: kubevirt-hostpath-provisioner
  postgres_storage_class: kubevirt-hostpath-provisioner
  redis_storage_class: kubevirt-hostpath-provisioner
  # We have a little over 10GB free on GHA VMs/instances
  file_storage_size: "10Gi"
  pulp_settings:
    api_root: "/api/galaxy/pulp/"
  content:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
  worker:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
  web:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 800m
        memory: 1Gi
