---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: delegated
lint: |
  set -e
  yamllint -d "{extends: relaxed, rules: {line-length: {max: 120}}}" .
platforms:
  - name: cluster
    groups:
      - k8s
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: debug
      callback_whitelist: profile_tasks
  lint: |
    set -e
    ansible-lint
  inventory:
    group_vars:
      all:
        namespace: ${TEST_OPERATOR_NAMESPACE:-osdk-test}
    host_vars:
      localhost:
        ansible_python_interpreter: '{{ ansible_playbook_python }}'
        build_dir: ${MOLECULE_PROJECT_DIRECTORY}/build
        deploy_dir: ${MOLECULE_PROJECT_DIRECTORY}/deploy
        crds_dir: ${MOLECULE_PROJECT_DIRECTORY}/deploy/crds
        operator_image: ${OPERATOR_IMAGE:-"quay.io/fabricio_aguiar/pulp-operator:latest"}
        operator_pull_policy: ${OPERATOR_PULL_POLICY:-"Always"}
  env:
    K8S_AUTH_KUBECONFIG: ${KUBECONFIG:-"~/.kube/config"}
verifier:
  name: ansible
  lint: |
    set -e
    ansible-lint
