images:
  - pulpcore_master:
      image_name: pulpcore
      tag: latest
      container_file: Containerfile.core
      # Must specify egg name here so that the Dockerfile can specify the
      # setuptools extra of postgres
      pulpcore: git+https://github.com/pulp/pulpcore.git#egg=pulpcore
  - galaxy_master:
      image_name: galaxy
      tag: latest
      container_file: Containerfile.core
      pulpcore: git+https://github.com/pulp/pulpcore.git@3.11#egg=pulpcore
      plugins:
        - "git+https://github.com/pulp/pulp_container.git@2.5"
        - "git+https://github.com/ansible/galaxy_ng.git"
registry: quay.io
project: pulp
