---
- name: Generate token authentication keys
  shell: |-
    openssl ecparam -genkey -name prime256v1 -noout -out /tmp/private_key.pem
    openssl ec -in /tmp/private_key.pem -pubout -out /tmp/public_key.pem

- name: Create token authentication secret
  k8s:
    apply: true
    definition: "{{ lookup('template', 'pulp-container-auth.secret.yaml.j2') }}"

- name: Get container token configuration
  k8s_info:
    kind: Secret
    namespace: '{{ ansible_operator_meta.namespace }}'
    name: '{{ container_token_secret }}'
  register: _container_token_configuration
  no_log: "{{ no_log }}"
