---
- name: Set default DB fields encryption secret name
  set_fact:
    db_fields_encryption_secret: '{{ meta.name }}-db-fields-encryption'
    cacheable: yes
  when: db_fields_encryption_secret is undefined

- name: Check for specified DB fields encryption configuration
  k8s_info:
    kind: Secret
    namespace: '{{ meta.namespace }}'
    name: '{{ db_fields_encryption_secret }}'
  register: _db_fields_encryption_secret
  no_log: true

- block:
    - name: Generate Pulp Database Encryption Key
      shell: |
        from cryptography.fernet import Fernet
        with open("/tmp/fernet", "wb") as key_file:
            key_file.write(Fernet.generate_key())
      args:
        executable: /usr/bin/python3
      no_log: true

    - name: Store DB fields encryption key
      set_fact:
        db_fields_encryption_key: "{{ lookup('file', '/tmp/fernet') }}"
      no_log: true

    - name: Create DB fields encryption secret
      k8s:
        apply: true
        definition: "{{ lookup('template', 'pulp-db-fields-encryption.secret.yaml.j2') }}"
      no_log: true

  when: not _db_fields_encryption_secret['resources'] | default([]) | length
