name: Pulp CI
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  schedule:
    # * is a special character in YAML so you have to quote this string
    # runs at 3:00 UTC daily
    - cron: '00 3 * * *'
jobs:
  insta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # by default, it uses a depth of 1
          # this fetches all history so that we can read each commit
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install httpie
        run: |
          echo ::group::HTTPIE
          sudo apt-get update -yq
          sudo -E apt-get -yq --no-install-suggests --no-install-recommends install httpie
          echo ::endgroup::
          echo "HTTPIE_CONFIG_DIR=$GITHUB_WORKSPACE/.ci/assets/httpie/" >> $GITHUB_ENV
          echo "IMG=quay.io/pulp/pulp-operator:latest" >> $GITHUB_ENV
          echo "CI_TEST=true" >> $GITHUB_ENV
        shell: bash
      - name: Start minikube
        run: |
          minikube start --vm-driver=docker --extra-config=apiserver.service-node-port-range=80-32000
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Setup a minikube docker env
        run: minikube -p minikube docker-env | grep "export" | awk '{$1= ""; print $0}' >> $GITHUB_ENV
      - name: Build Operator
        run: |
          echo ::group::SDK
          CURRENT_VERSION=$(head -1 ./build/Dockerfile  | cut -d ":" -f 2)
          sudo wget https://github.com/operator-framework/operator-sdk/releases/download/$CURRENT_VERSION/operator-sdk-$CURRENT_VERSION-x86_64-linux-gnu -O /usr/local/bin/operator-sdk
          sudo chmod +x /usr/local/bin/operator-sdk
          echo ::endgroup::
          eval $(minikube -p minikube docker-env)
          sudo -E operator-sdk build quay.io/pulp/pulp-operator:latest
          sudo -E docker images
        shell: bash
      - name: Test insta-demo
        run: sudo -E insta-demo/pulp-insta-demo.sh -m
        shell: bash
      - name: Logs
        if: always()
        run: |
          sudo docker images
          sudo -E kubectl logs -l app.kubernetes.io/name=pulp-operator -c pulp-operator --tail=10000
          sudo -E kubectl logs -l app.kubernetes.io/name=pulp-api --tail=10000
          sudo -E kubectl logs -l app.kubernetes.io/name=pulp-content --tail=10000
          sudo -E kubectl logs -l app.kubernetes.io/name=pulp-worker --tail=10000
          sudo -E kubectl logs -l app.kubernetes.io/name=pulp-resource-manager --tail=10000
          sudo -E kubectl logs -l app.kubernetes.io/name=pulp-web --tail=10000
          http --timeout 30 --check-status --pretty format --print hb http://localhost:24880/pulp/api/v3/status/

  components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # by default, it uses a depth of 1
          # this fetches all history so that we can read each commit
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install httpie
        run: |
          echo ::group::HTTPIE
          sudo apt-get update -yq
          sudo -E apt-get -yq --no-install-suggests --no-install-recommends install httpie
          echo ::endgroup::
          echo "HTTPIE_CONFIG_DIR=$GITHUB_WORKSPACE/.ci/assets/httpie/" >> $GITHUB_ENV
          echo "IMG=quay.io/pulp/pulp-operator:latest" >> $GITHUB_ENV
          echo "CI_TEST=true" >> $GITHUB_ENV
        shell: bash
      - name: Start minikube
        run: |
          minikube start --vm-driver=docker --extra-config=apiserver.service-node-port-range=80-32000
        # now you can run kubectl to see the pods in the cluster
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Setup a minikube docker env
        run: minikube -p minikube docker-env | grep "export" | awk '{$1= ""; print $0}' >> $GITHUB_ENV
      - name: Build Operator
        run: |
          echo ::group::SDK
          CURRENT_VERSION=$(head -1 ./build/Dockerfile  | cut -d ":" -f 2)
          sudo wget https://github.com/operator-framework/operator-sdk/releases/download/$CURRENT_VERSION/operator-sdk-$CURRENT_VERSION-x86_64-linux-gnu -O /usr/local/bin/operator-sdk
          sudo chmod +x /usr/local/bin/operator-sdk
          echo ::endgroup::
          eval $(minikube -p minikube docker-env)
          sudo -E operator-sdk build quay.io/pulp/pulp-operator:latest
          sudo -E docker images
        shell: bash
      - name: Deploy pulp-operator to K8s
        run: sudo -E ./up.sh
        shell: bash
      - name: Check and wait pulp-operator deploy
        run: .ci/scripts/pulp-operator-check-and-wait.sh -m
        shell: bash
      - name: Test all components
        run: |
          git clone --depth=1 https://github.com/pulp/pulp_file.git
          .ci/scripts/retry.sh 3 ".ci/scripts/pulp_file-tests.sh -m"
        shell: bash
        env:
          PY_COLORS: '1'
      - name: Logs
        if: always()
        run: |
          sudo docker images
          sudo -E kubectl logs -l app.kubernetes.io/name=pulp-operator -c pulp-operator --tail=10000
          sudo -E kubectl logs -l app.kubernetes.io/name=pulp-api --tail=10000
          sudo -E kubectl logs -l app.kubernetes.io/name=pulp-content --tail=10000
          sudo -E kubectl logs -l app.kubernetes.io/name=pulp-worker --tail=10000
          sudo -E kubectl logs -l app.kubernetes.io/name=pulp-resource-manager --tail=10000
          sudo -E kubectl logs -l app.kubernetes.io/name=pulp-web --tail=10000
          http --timeout 30 --check-status --pretty format --print hb http://localhost:24880/pulp/api/v3/status/

  galaxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # by default, it uses a depth of 1
          # this fetches all history so that we can read each commit
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install httpie
        run: |
          echo ::group::HTTPIE
          sudo apt-get update -yq
          sudo -E apt-get -yq --no-install-suggests --no-install-recommends install httpie
          echo ::endgroup::
          echo "HTTPIE_CONFIG_DIR=$GITHUB_WORKSPACE/.ci/assets/httpie/" >> $GITHUB_ENV
          echo "IMG=quay.io/pulp/pulp-operator:latest" >> $GITHUB_ENV
          echo "CI_TEST=true" >> $GITHUB_ENV
        shell: bash
      - name: Start minikube
        run: |
          minikube start --vm-driver=docker --extra-config=apiserver.service-node-port-range=80-32000
        # now you can run kubectl to see the pods in the cluster
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Setup a minikube docker env
        run: minikube -p minikube docker-env | grep "export" | awk '{$1= ""; print $0}' >> $GITHUB_ENV
      - name: Build Operator
        run: |
          echo ::group::SDK
          CURRENT_VERSION=$(head -1 ./build/Dockerfile  | cut -d ":" -f 2)
          sudo wget https://github.com/operator-framework/operator-sdk/releases/download/$CURRENT_VERSION/operator-sdk-$CURRENT_VERSION-x86_64-linux-gnu -O /usr/local/bin/operator-sdk
          sudo chmod +x /usr/local/bin/operator-sdk
          echo ::endgroup::
          eval $(minikube -p minikube docker-env)
          sudo -E operator-sdk build quay.io/pulp/pulp-operator:latest
          sudo -E docker images
        shell: bash
      - name: Deploy pulp-operator to K8s
        run: sudo -E CI_TEST=galaxy ./up.sh
        shell: bash
      - name: Check and wait pulp-operator deploy
        run: .ci/scripts/pulp-operator-check-and-wait.sh -m
        shell: bash
      - name: Test
        run: sudo -E .ci/scripts/galaxy_ng-tests.sh -m
        shell: bash
      - name: Logs
        if: always()
        run: |
          sudo docker images
          sudo -E kubectl logs -l app.kubernetes.io/name=pulp-operator -c pulp-operator --tail=10000
          sudo -E kubectl logs -l app.kubernetes.io/name=pulp-api --tail=10000
          sudo -E kubectl logs -l app.kubernetes.io/name=pulp-content --tail=10000
          sudo -E kubectl logs -l app.kubernetes.io/name=pulp-worker --tail=10000
          sudo -E kubectl logs -l app.kubernetes.io/name=pulp-resource-manager --tail=10000
          sudo -E kubectl logs -l app.kubernetes.io/name=pulp-web --tail=10000
          http --timeout 30 --check-status --pretty format --print hb http://localhost:24880/pulp/api/v3/status/

  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # by default, it uses a depth of 1
          # this fetches all history so that we can read each commit
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - name: Install httpie
        run: |
          echo ::group::HTTPIE
          sudo apt-get update -yq
          sudo -E apt-get -yq --no-install-suggests --no-install-recommends install httpie
          echo ::endgroup::
          echo "HTTPIE_CONFIG_DIR=$GITHUB_WORKSPACE/.ci/assets/httpie/" >> $GITHUB_ENV
          echo "IMG=quay.io/pulp/pulp-operator:latest" >> $GITHUB_ENV
          echo "CI_TEST=true" >> $GITHUB_ENV
        shell: bash
      - name: Install
        run: |
          pip install --upgrade pip
          sudo apt remove ansible
          pip install ansible==4.0.0 molecule[docker,lint] six openshift==0.11.0 jmespath pipdeptree
          ansible-galaxy collection install --force community.docker
          ansible --version
          pipdeptree
      - name: Molecule
        run: .ci/scripts/molecule.sh
        shell: bash
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
      - name: After failure
        if: failure()
        run: |
          docker exec -it osdk-test-control-plane journalctl -S today --no-pager

  deploy:
    runs-on: ubuntu-latest
    needs: [insta, components, molecule, galaxy]
    strategy:
      fail-fast: false
      # Testing different python versions because of
      # https://pulp.plan.io/issues/5768#note-17
      matrix:
        include:
          - CI_TEST: true
          - CI_TEST: galaxy
    steps:
      - uses: actions/checkout@v2
        with:
          # by default, it uses a depth of 1
          # this fetches all history so that we can read each commit
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install httpie
        run: |
          echo ::group::HTTPIE
          sudo apt-get update -yq
          sudo -E apt-get -yq --no-install-suggests --no-install-recommends install httpie
          echo ::endgroup::
          echo "HTTPIE_CONFIG_DIR=$GITHUB_WORKSPACE/.ci/assets/httpie/" >> $GITHUB_ENV
          echo "IMG=quay.io/pulp/pulp-operator:latest" >> $GITHUB_ENV
          echo "CI_TEST=true" >> $GITHUB_ENV
        shell: bash
      - name: Start minikube
        run: |
          minikube start --vm-driver=docker --extra-config=apiserver.service-node-port-range=80-32000
        # now you can run kubectl to see the pods in the cluster
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Setup a minikube docker env
        run: minikube -p minikube docker-env | grep "export" | awk '{$1= ""; print $0}' >> $GITHUB_ENV
      - name: Build Operator
        run: |
          echo ::group::SDK
          CURRENT_VERSION=$(head -1 ./build/Dockerfile  | cut -d ":" -f 2)
          sudo wget https://github.com/operator-framework/operator-sdk/releases/download/$CURRENT_VERSION/operator-sdk-$CURRENT_VERSION-x86_64-linux-gnu -O /usr/local/bin/operator-sdk
          sudo chmod +x /usr/local/bin/operator-sdk
          echo ::endgroup::
          eval $(minikube -p minikube docker-env)
          sudo -E operator-sdk build quay.io/pulp/pulp-operator:latest
          sudo -E docker images
        shell: bash
      - name: Setting secrets
        run: python3 .github/workflows/scripts/secrets.py "$SECRETS_CONTEXT"
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
      - name: Add stable images
        if: github.event_name != 'schedule'
        run: |
          pip install aiohttp packaging PyYAML sh
          CI_TEST=${{ matrix.CI_TEST }} python3 .ci/scripts/images.py
      - name: Testing images
        run: |
          git clone --depth=1 https://github.com/pulp/pulp_file.git
          CI_TEST=${{ matrix.CI_TEST }} .github/workflows/scripts/build_images.sh
          CI_TEST=${{ matrix.CI_TEST }} .github/workflows/scripts/test_images.sh -m
        shell: bash
      - name: Deploy Operator images
        run: CI_TEST=${{ matrix.CI_TEST }} .ci/scripts/deploy.sh -i
        shell: bash
      - name: Deploy Pulp/Galaxy images
        run: CI_TEST=${{ matrix.CI_TEST }} .ci/scripts/deploy.sh
        shell: bash
      - name: Define QUAY_IMAGE_TAG environment variable
        if: github.event_name == 'schedule'
        run: |
          TEST=${{ matrix.CI_TEST }}
          echo $TEST
          if [[ "$TEST" == "galaxy" ]]; then
            CURRENT_VERSION=$(docker run quay.io/pulp/galaxy:latest bash -c 'pip3 show galaxy_ng | sed -n -e "s/Version: //p"')
          else
            CURRENT_VERSION=$(docker run quay.io/pulp/pulp:latest bash -c 'pip3 show pulpcore | sed -n -e "s/Version: //p"')
          fi
          echo $CURRENT_VERSION
          echo "QUAY_IMAGE_TAG=$CURRENT_VERSION-$(date +%j)" >> $GITHUB_ENV
          echo "QUAY_EXPIRE=14" >> $GITHUB_ENV
        shell: bash
      - name: Deploy Pulp/Galaxy nightly build
        if: github.event_name == 'schedule'
        run: |
          CI_TEST=${{ matrix.CI_TEST }} .github/workflows/scripts/build_images.sh
          CI_TEST=${{ matrix.CI_TEST }} .ci/scripts/deploy.sh
        shell: bash
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
      - name: Logs
        if: always()
        run: |
          sudo docker images
          sudo -E kubectl logs -l app.kubernetes.io/name=pulp-operator -c pulp-operator --tail=10000
          sudo -E kubectl logs -l app.kubernetes.io/name=pulp-api --tail=10000
          sudo -E kubectl logs -l app.kubernetes.io/name=pulp-content --tail=10000
          sudo -E kubectl logs -l app.kubernetes.io/name=pulp-worker --tail=10000
          sudo -E kubectl logs -l app.kubernetes.io/name=pulp-resource-manager --tail=10000
          sudo -E kubectl logs -l app.kubernetes.io/name=pulp-web --tail=10000
          http --timeout 30 --check-status --pretty format --print hb http://localhost:24880/pulp/api/v3/status/
