name: Pulp Compose

on:
  schedule:
    - cron: '15 3 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/pulp_images.yml'
      - 'containers/compose/**'
      - 'containers/podman-compose.yml'

jobs:
  compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # by default, it uses a depth of 1
          # this fetches all history so that we can read each commit
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install httpie and podman-compose
        run: |
          echo ::group::HTTPIE
          sudo apt-get update -yq
           apt-get -yq --no-install-suggests --no-install-recommends install httpie
          echo ::endgroup::
          echo "HTTPIE_CONFIG_DIR=$GITHUB_WORKSPACE/.ci/assets/httpie/" >> $GITHUB_ENV
          pip install podman-compose
        shell: bash
      - name: Compose up
        run: |
          cd containers
          podman-compose up -d
          sleep 30
          for _ in $(seq 20)
          do
            sleep 3
            if curl --fail http://localhost:24817/pulp/api/v3/status/ > /dev/null 2>&1
            then
              break
            fi
          done
          curl --fail http://localhost:24817/pulp/api/v3/status/ | jq
        shell: bash
      - name: Test all components
        run: |
          git clone --depth=1 https://github.com/pulp/pulp_ansible.git
          git clone --depth=1 https://github.com/pulp/pulp_container.git
          .ci/scripts/pulp_tests.sh
        shell: bash
        env:
          PY_COLORS: '1'
      - name: Logs
        if: always()
        run: |
          podman ps -a
          sudo -E podman images -a
          podman logs --tail=10000 containers_pulp_api_1
          podman logs --tail=10000 containers_pulp_content_1
          podman logs --tail=10000 containers_pulp_worker_1
          podman logs --tail=10000 containers_pulp_worker_2
          podman logs --tail=10000 containers_pulp_web_1
          http --follow --timeout 30 --check-status --pretty format --print hb http://localhost:24817/pulp/api/v3/status/ || true
