name: Pulp Images

on:
  schedule:
    - cron: '15 3 * * *'
  workflow_dispatch:

jobs:
  compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # by default, it uses a depth of 1
          # this fetches all history so that we can read each commit
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install httpie and podman-compose
        run: |
          echo ::group::HTTPIE
          sudo apt-get update -yq
          sudo -E apt-get -yq --no-install-suggests --no-install-recommends install httpie
          echo ::endgroup::
          echo "HTTPIE_CONFIG_DIR=$GITHUB_WORKSPACE/.ci/assets/httpie/" >> $GITHUB_ENV
          pip install podman-compose
        shell: bash
      - name: Compose up
        run: |
          cd containers
          podman-compose up -d
          sleep 30
        shell: bash
      - name: Test all components
        run: |
          git clone --depth=1 https://github.com/pulp/pulp_file.git
          .ci/scripts/retry.sh 3 ".ci/scripts/pulp_file-tests.sh"
        shell: bash
        env:
          PY_COLORS: '1'
      - name: Logs
        if: always()
        run: |
          podman ps -a
          podman images -a
          podman logs --tail=10000 containers_pulp_api_1
          podman logs --tail=10000 containers_pulp_content_1
          podman logs --tail=10000 containers_pulp_worker_1
          podman logs --tail=10000 containers_pulp_worker_2
          podman logs --tail=10000 containers_pulp_web_1
          http --timeout 30 --check-status --pretty format --print hb http://localhost:24817/pulp/api/v3/status/ || true
